# Generated by Django 4.2.2 on 2023-06-30 03:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.RemoveField(
            model_name='trade_post',
            name='status_choice',
        ),
        migrations.AlterField(
            model_name='trade_post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='trade_post',
            name='trade_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradebook.tradecategory'),
            preserve_default=False,
        ),
    ]
