# Generated by Django 4.2.2 on 2023-06-22 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradebook', '0002_alter_post_status_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='trade_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog/images/%Y/%m/%d/')),
                ('status_choice', models.CharField(choices=[('waiting', '판매대기'), ('buying', '거래중'), ('selling', '판매중'), ('finish', '거래종료')], default='waiting', max_length=10)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
