# Generated by Django 4.2.2 on 2023-06-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0003_trade_post_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_post',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade_post',
            name='status_choice',
            field=models.CharField(choices=[('판매대기', '판매대기'), ('거래중', '거래중'), ('판매중', '판매중'), ('거래완료', '거래완료')], default='waiting', max_length=10),
        ),
    ]
