# Generated by Django 4.2.2 on 2023-06-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('userpw', models.IntegerField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=30)),
                ('address', models.TextField()),
                ('regdate', models.DateTimeField()),
            ],
        ),
    ]
