# Generated by Django 4.2.2 on 2023-06-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
