# Generated by Django 4.2.2 on 2023-06-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_category_product_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='Category_product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
