# Generated by Django 4.2.2 on 2023-06-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
