# Generated by Django 4.2.2 on 2023-06-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_memo_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='is_hidden',
        ),
    ]
