# Generated by Django 4.2.2 on 2023-06-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_cuscomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CusComment',
        ),
    ]
