# Generated by Django 4.2.2 on 2023-06-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='community/images/%y/%m/%d/'),
        ),
    ]
