# Generated by Django 4.2.2 on 2023-06-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='attach',
        ),
    ]
