# Generated by Django 4.2.2 on 2023-06-26 09:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_rename_likes_post_liked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attach',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
