# Generated by Django 4.2.2 on 2023-06-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenbooks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
