# Generated by Django 4.2.2 on 2023-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='url',
        ),
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, upload_to='goodds/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
