# Generated by Django 4.2.2 on 2023-06-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_bname_goods_name_goods_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/%Y/%m/%d'),
        ),
    ]
