# Generated by Django 4.2.2 on 2023-06-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='writer',
            new_name='author',
        ),
    ]
